### PR TITLE
Julia code for MPL figure 1.16 (1D and 2D regression)

### LINKED ISSUE #3: Julia code for PML1 figure 1.6

### PR DESCRIPTION
**Pull request by ageorgou**
Closes #3.

Based on [the original Python notebook](https://github.com/probml/pyprobml/blob/5602525b2e10686beca4e1dbf8c2bc52888271aa/notebooks/book1/01/linreg_2d_surface_demo.ipynb).

Regression computations (training and prediction) provided by other packages, not shown here!

### CODE REVIEW

File: probabilistic-machine-learning-an-introduction/julia/linreg_2d_surface_demo.jl [hunk 1]
```diff
@@ -0,0 +1,1180 @@
...
+begin
+	using Downloads
+	using MAT
+	using GLM
+	using Plots
+end
+
+# ╔═╡ b0c55ed6-2603-11ed-2883-d303f1fd983f
+function getData(url)
+	# url = "https://raw.githubusercontent.com/probml/probml-data/main/data/moteData/moteData.mat";
```
Comment (matt-graham) [inline probabilistic-machine-learning-an-introduction/julia/linreg_2d_surface_demo.jl]:
```suggestion
```
Probably can be removed as duplicated as argument below

**Review by matt-graham — APPROVED** [review]
Looks good to me! At the moment this uses a slightly different directory structure from that I used in #2 and in the [`README.md`](https://github.com/UCL-ARC/csml-reading-group/blob/main/README.md) in that it is within a language specific directory under the book directory rather than further broken down by chapter. I think having a single directory per language as you do here might make more sense to avoid having to repeatedly create the same subdirectories for each chapter, but I wonder if we should then use some form of naming convention / prefix to make it clearer which chapter (and potentially) each notebook is associated with - for example `probabilistic-machine-learning-an-introduction/julia/01_07_linreg_2d_surface_demo.jl` - so that if / when we have more examples it is easier to find the ones for each chapter?
